Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -65,9 +65,12 @@ jobs:
           curl -X POST -s -S -L -u ${{ secrets.JENKINS_TOKEN }} \
             -d 'RELEASE_DEB_BUILD=${{ github.event.inputs.deb_version }}' \
             ${{ secrets.JENKINS_URL }}/job/release.deb.publish/buildWithParameters
+          [ $? -ne 0 ] && echo "::error:: Failed to start DEB build" && exit 1
 
           echo "DEB_BUILD_NUMBER=$(curl -s -u ${{ secrets.JENKINS_TOKEN }} "${{ secrets.JENKINS_URL }}/job/release.deb.publish/lastBuild/api/json" | jq '.number')" >> $GITHUB_ENV
+          [ $? -ne 0 ] && echo "::error:: Failed to get DEB build number" && exit 1
           echo "RPM_BUILD_NUMBER=$(curl -s -u ${{ secrets.JENKINS_TOKEN }} "${{ secrets.JENKINS_URL }}/job/release.deb.publish/lastBuild/api/json" | jq '.number')" >> $GITHUB_ENV
+          [ $? -ne 0 ] && echo "::error:: Failed to get RPM build number" && exit 1
 
           # curl -X POST -s -S -L -u ${{ secrets.JENKINS_TOKEN }} \
           #   -d 'docspace_rpm_selector=<SpecificBuildSelector><buildNumber>${{ github.event.inputs.rpm_version }}</buildNumber></SpecificBuildSelector>' \
