Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -65,25 +65,19 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          PR_NUMBER=$(timeout 60 bash -c 'while true; do
-            PR_NUMBER=$(gh pr list --repo "${{ github.repository_owner }}/${{ matrix.repo }}" \
+          PR_NUMBER=$(timeout 60 bash -c 'while :; do
+            NUM=$(gh pr list --repo "${{ github.repository_owner }}/${{ matrix.repo }}" \
               --base "${{ github.event.inputs.target_branch }}" --head "${{ github.event.inputs.branch }}" \
               --state open --json number --jq ".[0].number")
-            if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "UNKNOWN" ]; then
-              echo $PR_NUMBER && break
-            fi
-            sleep 2
+            [ -n "$NUM" ] && [ "$NUM" != "UNKNOWN" ] && echo $NUM && exit 0
+            sleep 2 
           done')
 
-          if [ -z "$PR_NUMBER" ]; then
-            echo "::warning::Failed to retrieve PR number for ${{ matrix.repo }}"
-            exit 1
-          fi
-
-          MERGEABLE_STATUS=$(gh pr view $PR_NUMBER --repo "${{ github.repository_owner }}/${{ matrix.repo }}" --json mergeable --jq '.mergeable')
-          if [ "$MERGEABLE_STATUS" = "MERGEABLE" ]; then
-            echo "Merging PR #$PR_NUMBER in ${{ matrix.repo }}"
-            gh pr merge $PR_NUMBER --merge --delete-branch
+          [ -z "$PR_NUMBER" ] && echo "::warning::Failed to retrieve PR number for ${{ matrix.repo }}" && exit 1
+          MERGEABLE_STATUS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository_owner }}/${{ matrix.repo }} --json mergeable --jq '.mergeable')
+          
+          if [ "${MERGEABLE_STATUS}" = "MERGEABLE" ]; then
+            gh pr merge ${PR_NUMBER} --merge --delete-branch
           else
             echo "::warning::PR #$PR_NUMBER in ${{ matrix.repo }} is not mergeable or contains conflicts."
           fi
@@ -115,7 +109,8 @@ jobs:
 
               [ "${PR_STATE}" = "MERGED" ] && ((MERGED++))
               [ "${PR_STATE}" = "NOT_FOUND" ] && REPOS=$(echo "${REPOS}" | awk -v repo="${REPO}" '{for (i=1; i<=NF; i++) if ($i != repo) printf "%s ", $i; print ""}')
-            done && echo "------------------------------------------------"
+            done
+            printf '%.0s-' {1..48}; echo
             [ "${MERGED}" -eq "$(echo ${REPOS} | wc -w)" ] && break
             sleep 5
           done
