Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -50,8 +50,7 @@ jobs:
       - name: Check branch existence
         run: |
           if ! gh api repos/${{ github.repository_owner }}/${{ matrix.repo }}/git/ref/heads/${{ github.event.inputs.branch }} --silent; then
-            echo "::error::Branch '${{ github.event.inputs.branch }}' does not exist in repository ${{ matrix.repo }}"
-            exit 1
+            echo "::error::Branch '${{ github.event.inputs.branch }}' does not exist in repository ${{ matrix.repo }}" && exit 1
           fi
 
       - name: Check commits difference
@@ -94,8 +93,7 @@ jobs:
           done;')
 
           if [ -z "${PR_NUMBER}" ]; then
-            echo "::error::Failed to find open PR in ${{ matrix.repo }}"
-            exit 1
+            echo "::error::Failed to find open PR in ${{ matrix.repo }}" && exit 1
           fi
 
           MERGEABLE_STATUS=$(gh pr view "${PR_NUMBER}" \
