Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -58,8 +58,8 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          PR_NUMBER=$(gh pr list --repo ${{ github.repository_owner }}/${{ matrix.repo }} --base ${{ github.event.inputs.target_branch }} --head "${{ github.event.inputs.branch }}" --state open --json number --jq ".[0].number")
-          [ -n "${PR_NUMBER}" ] && MERGEABLE_STATUS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository_owner }}/${{ matrix.repo }} --json mergeable --jq '.mergeable')
+          PR_NUMBER=$(timeout 60 bash -c 'while :; do PR_NUMBER=$(gh pr list --repo ${{ github.repository_owner }}/${{ matrix.repo }} --base ${{ github.event.inputs.target_branch }} --head "${{ github.event.inputs.branch }}" --state open --json number --jq ".[0].number"); [[ -n "$PR_NUMBER" && "$PR_NUMBER" != "UNKNOWN" ]] && echo $PR_NUMBER; sleep 2; done;')
+          [ -n "${PR_NUMBER}" ] && MERGEABLE_STATUS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository_owner }}/${{ matrix.repo }} --json mergeable --jq '.mergeable') || echo "::warning::Failed to get a PR number for ${{ matrix.repo }}"
           echo ${MERGEABLE_STATUS}
           if [ "${MERGEABLE_STATUS}" = "MERGEABLE" ]; then
             gh pr merge ${PR_NUMBER} --merge --delete-branch
@@ -136,7 +136,7 @@ jobs:
         run: |
           VERSION="${{ github.event.inputs.version }}"; VERSION="${VERSION#v}.1"
           curl -X POST \
-              -u "${{ secrets.USERNAME }}:${{ secrets.DOCKER_TOKEN }}" \
+              -u "${{ secrets.USERNAME }}:${{ secrets.GH_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository_owner }}/DocSpace-buildtools/actions/workflows/106393860/dispatches" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               --data "{\"ref\": \"${{ github.ref_name }}\", \"inputs\": {\"release_version\": \"${VERSION}\", \"source_version\": \"${{ github.event.inputs.source_docker_version }}\"}}"
